project:
  type: website
  output-dir: docs

website:
  title: "maelan-hauswirth.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Blog.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

